name: Create Pull Request
on:
  push:
    branches: 
      - '*dev'
jobs:
  Create-Pull-Request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.12.1
        with:
          commit-message: ${{ github.event.head_commit.message }}
          committer: ${{ github.event.head_commit.committer.name }} ${{ github.event.head_commit.committer.email }}
          branch: main
