name: Create Pull Request
on:
  push:
    branches: 
      - '*dev'
jobs:
  Create-Pull-Request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.PAT }}
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.12.1
        with:
          token: ${{ secrets.PAT }}
          branch: main
          title: ${{ github.event.head_commit.message }}
